# Generated by Django 4.1.7 on 2024-05-06 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='trailer_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
