# Generated by Django 4.1.7 on 2024-05-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movieinfo_trailer_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='trailer_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
