# Generated by Django 4.1.7 on 2024-05-08 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movieinfo_trailer_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='trailer_link',
            field=models.URLField(null=True),
        ),
    ]
